spring.application.name=hackaton

# MySQL Database
spring.r2dbc.url=${DATABASE_URL}
spring.r2dbc.username=${DATABASE_USERNAME}
spring.r2dbc.password=${DATABASE_PASSWORD}

# Server
server.port=${PORT:8080}

# OpenAPI settings
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
