spring.application.name=hackaton

# MySQL Database
spring.r2dbc.url=${DATABASE_URL}
spring.r2dbc.username=${DATABASE_USERNAME}
spring.r2dbc.password=${DATABASE_PASSWORD}

# Server
server.port=${PORT:8080}

# OpenAPI settings
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# R2DBC connection pool
spring.r2dbc.pool.initial-size=1
spring.r2dbc.pool.max-size=4
spring.r2dbc.pool.min-idle=0
spring.r2dbc.pool.max-idle-time=10m
